version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=agendapet
      - POSTGRES_PASSWORD=agendapet_password
      - POSTGRES_DB=agendapet_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: